### ISSUE TITLE
CSS Customization: Add Example for changing Avatar position

### ISSUE THREAD

**Issue by AlexTeusz** [Cognigy/WebchatWidget#158]
Hey @kwinto and @pedily ,

Could we please add the following example to the related CSS class documentation in `css-customization.md` in order to show that one could change the bot avatar position from left bottom to left top?

```css
[data-cognigy-webchat-root] [data-cognigy-webchat].webchat .webchat-message-row.bot {
  align-items: flex-start !important;
}
```
