### ISSUE TITLE
Docs: Image Gallery is missing [data-cognigy-webchat] to make it work

### ISSUE THREAD

**Issue by alexteusz** [Cognigy/WebchatWidget#258]
Hey,

In order to make the .webchat-carousel-template-frame work, the [data-cognigy-webchat] must be added to the command:

```css
* *webchat-carousel-template-frame*  
The frame that adds the "card styles" such as background-color or box-shadow.
```CSS
[data-cognigy-webchat-root] .webchat-carousel-template-frame {
  box-shadow: none;
}
```

working:

```css
* *webchat-carousel-template-frame*  
The frame that adds the "card styles" such as background-color or box-shadow.
```CSS
[data-cognigy-webchat-root] [data-cogngiy-webchat] .webchat-carousel-template-frame {
  box-shadow: none;
}
```
